server:
  port: 8085

spring:
  application:
    name: notification-service

  mail:
    host: ${SPRING_MAIL_HOST:smtp-relay.brevo.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:your_smtp_mail_username}
    password: ${SPRING_MAIL_PASSWORD:your_smtp_mail_password}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: ${SPRING_MAIL_FROM:your_email@example.com}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
