server:
  port: 8083
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://mysql:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#Razorpay configuration
razorpay:
  key-id: your_razorpay_key_id
  key-secret: your_razorpay_key_secret
  webhook-secret:

management:
  endpoints:
    web:
      exposure:
        include: health,info

